## 逐元素运算
relu运算和加法运算都是逐元素(element-wise)的运算，该运算独立地应用于张量中的每个元素。这样就非常适合大规模并行实现。

In [5]:
import numpy as np

x = np.random.randint(10,size=(2,4))
print("x:\n",x)
print("x.shape:",x.shape)

y = np.random.randint(10,size=(2,4))
print("y:\n",y)
print("y.shape:",y.shape)

x:
 [[0 3 8 1]
 [7 5 0 4]]
x.shape: (2, 4)
y:
 [[7 7 9 0]
 [8 5 4 8]]
y.shape: (2, 4)


In [4]:
sum = x + y
print("sum:\n",sum)

sum:
 [[ 4  8  8 13]
 [ 7  3  7 14]]


## 广播
如果2个不同形状的张量相加，较小的张量会被`广播`,以匹配较大张量的形状。

广播包含2步骤：
1. 较小的张量添加轴(叫做广播轴),使其ndim与较大的张量相同
2. 将较小的张量沿着新轴重复，使其形状与较大的张量相同

In [8]:
x = np.random.randint(10,size=(2,2))
y = np.random.randint(10,size=(1))

print("x:\n",x)
print("y:\n",y)

sum = x + y
print("sum:\n",sum)

x:
 [[3 1]
 [8 3]]
y:
 [2]
sum:
 [[ 5  3]
 [10  5]]


上面的代码就实现了`y`的广播。

注意：
1. 在真正实现过程中，不会创建新的张量，因为这样做非常低效
2. 重复的操作完全是虚拟的，只出现算法中，不会在内存中发生。

### 张量点积 (tensor product)
不要与逐元素的乘积弄混，最常见也是最有用的张量运算。

- `*`，逐元素的乘积运算
- `dot`,点积运算

In [9]:
x = np.random.randint(5,size=(3,))
y = np.random.randint(5,size=(3,))

print("x:\n",x)
print("y:\n",y)

z = np.dot(x,y)
print("z:\n",z)

x:
 [2 1 4]
y:
 [0 2 3]
z:
 14


In [4]:
x = np.random.randint(5,size=(2,4))
y = np.random.randint(5,size=(4,))

print("x:\n",x)
print("y:\n",y)

z = np.dot(x,y)
print("z:\n",z)
print("z.ndim",z.ndim)
print("z.shape",z.shape)

x:
 [[1 3 2 3]
 [3 4 2 0]]
y:
 [3 3 3 4]
z:
 [30 27]
z.ndim 1
z.shape (2,)



```
(a,b,c,d).(d,)>(a,b,c)

(a,b,c,d).(d,e)>(a,b,c,e)
```

![img](images/002-003.png)

